version: '2'
services:
  web:
    build: .
    image: dom_app:app
    environment:
      - PYTHONPATH=/pylib:/code
    command: ["bash", "-c", "python manage.py migrate && uwsgi --uid 1000 --gid 1000 --check-static dom  --wsgi-file server/wsgi.py --master --https 0.0.0.0:8107,SSL/cert_chain.crt,SSL/propmix.key"]
    volumes:
      - .:/code
      - /cluster_100G_01/lib:/pylib
    ports:
      - "8107:8107"
    container_name: dom_app_server
    
