host = 'https://dev-api.propmix.io/mlslite/icma/v1/GetListingsByRadius?'
Street_name = 'Street'
Radius_name = 'Radius'
MonthsBack_name = 'MonthsBack'
City_name = 'City'
State_name = 'State'
PropertyType_name = 'PropertyType'
PageSize_name = 'PageSize'
Longitude_name = 'Longitude'
Latitude_name = 'Latitude'
PageSize_Value = 400
Zip_name = 'Zip'
isZip_name = 'isZipON'
ZipON = 1

columnlist = ['Distance', 'LotSizeSquareFeet', 'LivingArea', 'BedroomsTotal',
              'BathroomsTotalInteger', 'StoriesTotal', 'YearBuilt',
              'FireplacesTotal', 'ListAgentFullName', 'MlsStatus']
columnlist_map = ['Distance', 'LotSizeArea', 'GLA', 'Beds',
                  'Baths', 'StoriesTotal', 'YearBuilt',
                  'FireplacesTotal',
                  'View', 'Cooling', 'Heating', 'PoolFeatures',
                  'WaterSource', 'Roof', 'FireplaceFeatures',
                  'ExteriorFeatures',
                  'InteriorFeatures', 'ParkingFeatures']
columnlist1 = ['UnparsedAddress',
               'City',
               'StateOrProvince',
               'PostalCode',
               'PostalCodePlus4',
               'ParcelNumber',
               'PropertyType',
               'PropertySubType',
               'LotSizeSquareFeet',
               'LivingArea',
               'ArchitecturalStyle',
               'Heating',
               'Cooling',
               'StoriesTotal',
               'Stories',
               'YearBuilt',
               'Roof',
               'ConstructionMaterials',
               'BedroomsTotal',
               'BathroomsTotalInteger',
               'ParkingFeatures',
               'PoolFeatures',
               'View',
               'PatioAndPorchFeatures',
               'Basement',
               'FireplacesTotal',
               'FireplaceYN',
               'FireplaceFeatures',
               'InteriorFeatures',
               'ExteriorFeatures',
               'OtherStructures',
               'PublicRemarks',
               'LotFeatures',
               'ZoningDescription',
               'CommunityFeatures',
               'ElementarySchoolDistrict',
               'MiddleOrJuniorSchoolDistrict',
               'HighSchoolDistrict',
               'ElementarySchool',
               'MiddleOrJuniorSchool',
               'HighSchool',
               'Appliances',
               'LotSizeDimensions',
               'Topography',
               'WaterSource',
               'ListingContractDate',
               'MlsStatus',
               'ListPrice',
               'ClosePrice',
               'CloseDate',
               'ListAgentStateLicense',
               'ListAgentFullName',
               'ListAgentPreferredPhone',
               'ListAgentEmail',
               'ListOfficeName',
               'ListOfficePhone',
               'ListOfficeEmail',
               'ListingId',
               'ListingKey',
               'ModificationTimestamp',
               'SI_FIPS',
               'SI_PropertyRefID',
               'SI_PriceperSquareFeet',
               'WaterfrontFeatures',
               'SI_WaterYN',
               'SI_DaysOnMarket',
               'ListingType',
               'OfficeAddress1',
               'SI_Address',
               'Latitude',
               'Longitude',
               'Distance',
               'ImageUrl',
               'SubjectProperty']
c_data_value = range(74)
c_data_name = ['Address',
               'City',
               'State',
               'Zip',
               'PostalCodePlus4',
               'ParcelNumber',
               'SI_PropertyType',
               'PropertySubType',
               'LotSizeArea',
               'GLA',
               'ArchitecturalStyle',
               'Heating',
               'Cooling',
               'StoriesTotal',
               'Stories',
               'YearBuilt',
               'Roof',
               'ConstructionMaterials',
               'Beds',
               'Baths',
               'ParkingFeatures',
               'PoolFeatures',
               'View',
               'PatioAndPorchFeatures',
               'Basement',
               'FireplacesTotal',
               'FireplaceYN',
               'FireplaceFeatures',
               'InteriorFeatures',
               'ExteriorFeatures',
               'OtherStructures',
               'PublicRemarks',
               'LotFeatures',
               'Zoning',
               'CommunityFeatures',
               'ElementarySchoolDistrict',
               'MiddleOrJuniorSchoolDistrict',
               'HighSchoolDistrict',
               'ElementarySchool',
               'MiddleOrJuniorSchool',
               'HighSchool',
               'EquipmentOrAppliances',
               'LotSizeDimensions',
               'Topography',
               'WaterSource',
               'ListingContractDate',
               'SI_Status',
               'ListPrice',
               'ClosePrice',
               'CloseDate',
               'ListAgentStateLicense',
               'ListAgentFullName',
               'ListAgentPreferredPhone',
               'ListAgentEmail',
               'ListOfficeName',
               'ListOfficePhone',
               'ListOfficeEmail',
               'ListingId',
               'ListingKey',
               'ModificationTimestamp',
               'SI_FIPS',
               'SI_PropertyRefID',
               'SI_PriceperSquareFeet',
               'WaterfrontFeatures',
               'SI_WaterYN',
               'SI_DaysOnMarket',
               'ListingType',
               'OfficeAddress1',
               'SI_Address',
               'Latitude',
               'Longitude',
               'Distance',
               'ImageUrl',
               'SubjectProperty']


xy_columns_name = ['View', 'Cooling',
                   'Heating', 'PoolFeatures',
                   'WaterSource', 'FireplaceFeatures',
                   'ExteriorFeatures', 'InteriorFeatures',
                   'Roof', 'ParkingFeatures']
data1_columns_name = ['Distance', 'LotSizeSquareFeet',
                      'LivingArea', 'BedroomsTotal', 'BathroomsTotalInteger',
                      'StoriesTotal', 'FireplacesTotal',
                      'YearBuilt']
