version: '2'
services:
  web:
    build: .
    image: hpiraw_app:app
    environment:
      - PYTHONPATH=/pylib:/code
    command: ["bash", "-c", "python manage.py migrate && uwsgi --uid 1000 --gid 1000 --check-static hpiipt --check-static hpiraw --check-static hpiraw3zip --wsgi-file server/wsgi.py --master --https 0.0.0.0:8105,SSL/cert_chain.crt,SSL/propmix.key"]
    volumes:
      - .:/code
      - /cluster_100G_01/lib:/pylib
    ports:
      - "8105:8105"
    container_name: hpiraw_app_server
    
